### ISSUE TITLE
Some paths are not escaped

### ISSUE THREAD

**Issue by Jojo4GH** [MontiCore/monticore#32]
Multiple paths don't get properly escaped in `de.monticore.generating.templateengine.reporting.reporter.IncGenCheckReporter`.
Spaces in those paths will cause an incorrect script and therefore errors.

Affected lines:
- https://github.com/MontiCore/monticore/blob/55244a75253844a9ae8826f17333fe6929f8d432/monticore-runtime/src/main/java/de/monticore/generating/templateengine/reporting/reporter/IncGenCheckReporter.java#L42
- https://github.com/MontiCore/monticore/blob/55244a75253844a9ae8826f17333fe6929f8d432/monticore-runtime/src/main/java/de/monticore/generating/templateengine/reporting/reporter/IncGenCheckReporter.java#L61
- https://github.com/MontiCore/monticore/blob/55244a75253844a9ae8826f17333fe6929f8d432/monticore-runtime/src/main/java/de/monticore/generating/templateengine/reporting/reporter/IncGenCheckReporter.java#L82
- https://github.com/MontiCore/monticore/blob/55244a75253844a9ae8826f17333fe6929f8d432/monticore-runtime/src/main/java/de/monticore/generating/templateengine/reporting/reporter/IncGenCheckReporter.java#L88
- https://github.com/MontiCore/monticore/blob/55244a75253844a9ae8826f17333fe6929f8d432/monticore-runtime/src/main/java/de/monticore/generating/templateengine/reporting/reporter/IncGenCheckReporter.java#L92

A similiar issue occurs in the gradle plugin while reading the checksums:
https://github.com/MontiCore/monticore/blob/db9b6cec46ef2cb84be1048ceed953e7719a4b79/monticore-generator/src/main/groovy/de/monticore/MCTask.groovy#L416
Here paths with spaces get split and the script throws exceptions.

**Comment by maritabreuer** [comment]
The bug was fixed in MCTask.groovy
