### ISSUE TITLE
token recognition error für Umlaute

### ISSUE THREAD

**Issue by DeltaBoss** [MontiCore/monticore#33]
Sowohl in keywords wie  
`Test = "ü" ding:FdlNumber;`

als auch in tokens wie  
`token GerName = ( 'a'..'z' | 'A'..'Z' | '_' | '$' | 'ä' | 'ö' | 'ü' | 'Ä' | 'Ö' | 'Ü')( 'a'..'z' | 'A'..'Z' | '_' | '0'..'9' | '$' | 'ä' | 'ö' | 'ü' | 'Ä' | 'Ö' | 'Ü' )*;`  

werden beim parsen Fehler der Form 
`[ERROR] ROOT Test.fdl:<2,2>: token recognition error at: 'ü'`
geworfen. Strings mit Umlauten lassen sich hingegen ohne Probleme parsen.

**Comment by maritabreuer** [comment]
Im Testprojekt sollte man sicherstellen, dass das Encoing richtig gesetzt ist. Das kann man z.B. in der gradle.properties einstellen:
org.gradle.jvmargs=-Dfile.encoding=UTF-8
